# Configuration for development environments: unless you are a Tobira
# developer, you are not interested in this file.

[general]
site_title.en = "Tobira Videoportal"

[db]
password = "tobira"

[meili]
key = "tobira"

[log]
level = "trace"

[auth]
mode = "login-proxy"

[auth.jwt]
signing_algorithm = "ES256"
secret_key = "jwt-key.pem"

[opencast]
host = "http://localhost:8081"

[sync]
user = "admin"
password = "opencast"
preferred_harvest_size = 3

[theme]
header_height = 36
logo.margin = 1
logo.large.path = "eth-logo.svg"
logo.large.resolution = [192, 31]
logo.small.path = "eth-logo.svg"
logo.small.resolution = [192, 31]
favicon = "favicon.svg"

color.navigation = "#1269B0"
color.accent = "#72791C"
color.danger = "#A8322D"
