[general]
site_title.en = "Tobira Test Deployment"

[db]
database = "tobira-{{ id }}"
user = "tobira-{{ id }}"
password = "tobira-{{ id }}"

[meili]
key = "tobira"
index_prefix = "tobira_{{ id }}_"

[http]
unix_socket = "/opt/tobira/{{ id }}/socket/tobira.sock"
unix_socket_permissions = 0o777

[auth]
mode = "login-proxy"
login_page.note.en = 'Dummy users: "augustus", "sabine" and "admin". Password for all: "tobira".'
login_page.note.de = 'Testnutzer: "augustus", "sabine" und "admin". Passwort für alle: "tobira".'

[auth.jwt]
signing_algorithm = "ES256"
# This is currently not created by scripts, but is expected to be generated there manually.
secret_key = "/opt/tobira/secret-jwt-key.pem"
expiration_time = "10min"

[log]
file = "/var/log/tobira/{{ id }}.log"

[opencast]
host = "https://oc.tobira.ethz.ch"

[sync]
user = "admin"
password = "{{ opencast_admin_password }}"
poll_period = "1min"

[theme]
header_height = 36
logo.margin = 1
logo.large.path = "logo-large.svg"
logo.large.resolution = [192, 31]
logo.small.path = "logo-large.svg"
logo.small.resolution = [192, 31]
favicon = "favicon.svg"

color.navigation = "#1269B0"
color.accent = "#72791C"
color.danger = "#A8322D"
