version: '2'

services:
  # A reverse proxy in front of Tobira that handles authentication via the login
  # handler.
  tobira-auth-proxy:
    image: nginx
    ports:
      - "3090:3090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./tobira-auth-proxy-nginx.conf:/etc/nginx/conf.d/default.conf:Z

  # A simple webserver handling login requests with some dummy users.
  tobira-login-handler:
    image: node:18
    ports:
      - "3091:3091"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ../dummy-login/dist/index.js:/usr/bin/login-handler.js:Z
    command: node /usr/bin/login-handler.js

  # A reverse proxy in front of Opencast that just adds some CORS headers
  # (required for the Tobira uploader, for example).
  opencast-cors-proxy:
    image: nginx
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./opencast-cors-proxy-nginx.conf:/etc/nginx/conf.d/default.conf:Z

  # A PostgreSQL database for Tobira.
  tobira-dev-database:
    image: docker.io/library/postgres:12
    restart: unless-stopped
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - tobira-dev-postgres:/var/lib/postgresql/data:Z
    environment:
      - POSTGRES_PASSWORD=tobira
      - POSTGRES_USER=tobira
      - POSTGRES_DB=tobira

  # A MeiliSearch for Tobira.
  tobira-meilisearch:
    image: getmeili/meilisearch:v1.4
    restart: unless-stopped
    ports:
      - 127.0.0.1:7700:7700
    volumes:
      - tobira-dev-meili:/data.ms:Z
    environment:
      - MEILI_NO_ANALYTICS=true
      - MEILI_MASTER_KEY=tobira


volumes:
  tobira-dev-postgres:
  tobira-dev-meili:
